# -*- coding: utf-8 -*-
"""Exploratory Dtata Analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RaMcQVpGt613vaJL_JFmh8pooV7LmTYG
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"/train.csv")
df

"""COLUMN TYPES

    >NUMERICAL-AGE,FARE,PASSENGERL***D
    >Categorical-Survived,Pclass,Sex,SibSp,Parch,Embarked
   >Mixed-Nmae,Ticket,Cabin

# ***AGE***


# ***CONCLUSIONS***


>Age is normally (almost) distributed
>20% of the values are missing
>there are some outliers
"""

df["Age"].describe()

df['Age'].plot(kind='hist',bins=30)

df['Age'].plot(kind='kde')

df['Age'].skew()

df['Age'].plot(kind='box')

df[df['Age'] > 65]

df['Age'].isnull().sum()/len(df['Age'])

"""# ***FARE***

# `CONCLUSIONS

# ***>The Data is Highly(positively)skewed***
# ***>Fare col actually contains the group fare & not the individual fare(This might be and issue)***
# **>We need to create a new col called individula fare** *italicized text*
"""

df['Fare'].describe()

df['Fare'].plot(kind='hist')

df['Fare'].plot(kind='box')

df['Fare'].plot(kind='kde')

df['Fare'].skew()

df[df['Fare'] > 250]

df['Fare'].isnull().sum()

"""# ***SURVIVED***

# ***CONCLUSIONS***

# ***> more than 60 percent are dead***
# ***> in numbers 549 passgenrs are dead***
# ***> there is no missing value***

---



---


"""

df['Survived'].value_counts()

df['Survived'].value_counts().plot(kind='bar')

df['Survived'].value_counts().plot(kind='pie',autopct='%0.1f%%')

"""# ***PCLASS ***

# ***CONCLUSIONS***
"""

df['Pclass'].value_counts()

df['Pclass'].value_counts().plot(kind='bar')

df['Pclass'].value_counts().plot(kind='pie',autopct="%0.1f%%")

df['Pclass'].isnull().sum()

"""# ***GENDER***

# ***CONCLUSIONS***
"""

df['Sex'].value_counts()

df['Sex'].value_counts().plot(kind='bar')

df['Sex'].value_counts().plot(kind='pie',autopct="%0.1f%%")

df['Sex'].isnull().sum()

df['SibSp'].value_counts()

df['SibSp'].value_counts().plot(kind='bar')

df['SibSp'].value_counts().plot(kind='pie',autopct="%0.1f%%")

df['SibSp'].isnull().sum()

df['Parch'].value_counts()

df['Parch'].value_counts().plot(kind='bar')

df['Parch'].value_counts().plot(kind='pie',autopct="%0.1f%%")

df['Parch'].isnull().sum()

df['Embarked'].value_counts()

df['Embarked'].value_counts().plot(kind='bar')

df['Embarked'].value_counts().plot(kind='pie',autopct="%0.1f%%")

df['Embarked'].isnull().sum()

df = pd.read_csv(r"/train.csv")
df

pd.crosstab(df['Survived'],df['Pclass'])

pd.crosstab(df['Survived'],df['Pclass'],normalize='columns')*100

sns.heatmap(pd.crosstab(df['Survived'],df['Pclass'],normalize='columns')*100)

pd.crosstab(df['Survived'],df['Sex'],normalize='columns')*100

sns.heatmap(pd.crosstab(df['Survived'],df['Sex'],normalize='columns')*100)

pd.crosstab(df['Survived'],df['Embarked'],normalize='columns')*100

pd.crosstab(df['Sex'],df['Embarked'],normalize='columns')*100

pd.crosstab(df['Pclass'],df['Embarked'],normalize='columns')*100

df[df['Survived'] == 1]['Age'].plot(kind='kde',label='Survived')
df[df['Survived'] == 0]['Age'].plot(kind='kde',label='Not Survived')

df[df['Pclass'] == 1]['Age'].mean()

"""# FEATURE ENG.. ON FARE COL"""

df['SibSp'].value_counts()

df[df['SibSp'] == 8]

69.55/11

df[df['Ticket'] == 'CA. 2343']

df[df['Name'].str.contains('Sage')]

df1 = pd.read_csv('/test.csv')
df1

pd.concat([df,df1])

df = pd.concat([df,df1])

df[df['Ticket'] == 'CA. 2343']

df['Ticket'].value_counts()

df[df['Ticket'] == 'CA 2144']

df[df['Ticket'] == '347082']

df['individual_fare'] = df['Fare']/(df['SibSp'] + df['Parch'] + 1)

df['individual_fare']

df['individual_fare'].plot(kind='box')

df[['individual_fare','Fare']].describe()

df

df['family_size'] = df['SibSp'] + df['Parch'] + 1

# family_type
# 1 -> alone
# 2-4 -> small
# >5 -> large

def transform_family_size(num):

  if num == 1:
    return 'alone'
  elif num>1 and num <5:
    return "small"
  else:
    return "large"

df['family_type'] = df['family_size'].apply(transform_family_size)

df

pd.crosstab(df['Survived'],df['family_type'],normalize = 'columns')*100

df

df['Name'].str.split(',').str.get(0)

df['surname'] = df['Name'].str.split(',').str.get(0)

df

df['Name'].str.split(',')

df['title'] = df['Name'].str.split(',').str.get(1).str.strip().str.split(' ').str.get(0)

df['title'].value_counts()

df['title'] = df['title'].str.replace('Rev','other')
df['title'] = df['title'].str.replace('Dr.','other')
df['title'] = df['title'].str.replace('Col.','other')
df['title'] = df['title'].str.replace('Major.','other')
df['title'] = df['title'].str.replace('Capt.','other')
df['title'] = df['title'].str.replace('the','other')
df['title'] = df['title'].str.replace('jonkheer','other')

temp_df = df[df['title'].isin(['Mr.','Miss.','Mrs.','Master.','ootherr'])]

temp_df

pd.crosstab(temp_df['Survived'],temp_df['title'])

pd.crosstab(temp_df['Survived'],temp_df['title'],normalize = 'columns')*100

df

df['Cabin'].isnull().sum()

df['Cabin'].isnull().sum()/len(df['Cabin'])

df['Cabin'].value_counts().head(15)

df['Cabin'].fillna('M',inplace=True)

df['Cabin'].value_counts()

df['deck'] = df['Cabin'].str[0]

df['deck'].value_counts()

pd.crosstab(df['deck'],df['Pclass'])

pd.crosstab(df['Survived'],df['deck'],normalize='columns')*100

pd.crosstab(df['deck'],df['Survived'],normalize='index').plot(kind='bar',stacked=True)

